#ifndef POLYQUAD_CONFIG_H
#define POLYQUAD_CONFIG_H

#define POLYQUAD_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define POLYQUAD_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define POLYQUAD_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define POLYQUAD_VERSION "@PROJECT_VERSION@"

#define POLYQUAD_BUILD_DATE "@POLYQUAD_BUILD_DATE@"

#cmakedefine POLYQUAD_HAVE_MPI @POLYQUAD_HAVE_MPI@
#cmakedefine POLYQUAD_HAVE_MULTIPRECISION @POLYQUAD_HAVE_MULTIPRECISION@

#define EIGEN_MATRIX_PLUGIN "utils/eigen_addons.hpp"

#endif // POLYQUAD_CONFIG_H
