#ifndef POLYQUAD_CONFIG_H
#define POLYQUAD_CONFIG_H

#define POLYQUAD_BUILD_DATE "@POLYQUAD_BUILD_DATE@"

#define POLYQUAD_VERSION_MAJOR @POLYQUAD_VERSION_MAJOR@

#define POLYQUAD_VERSION_MINOR @POLYQUAD_VERSION_MINOR@

#define POLYQUAD_VERSION "@POLYQUAD_VERSION@"

#cmakedefine POLYQUAD_HAVE_MPI

#define EIGEN_MATRIX_PLUGIN "utils/eigen_addons.hpp"

#endif // POLYQUAD_CONFIG_H
